/home/volkan/anaconda3/envs/adlr/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: [33mWARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Traceback (most recent call last):
  File "/home/volkan/31_Projects/adlr/tum-adlr-09/SAC-X/training.py", line 512, in <module>
    actorNet.save_checkpoint()
  File "/home/volkan/31_Projects/adlr/tum-adlr-09/SAC-X/model.py", line 163, in save_checkpoint
    torch.save(self.state_dict(), self.checkpoint_file)
  File "/home/volkan/anaconda3/envs/adlr/lib/python3.9/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/home/volkan/anaconda3/envs/adlr/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/volkan/anaconda3/envs/adlr/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/sac/actor_sac'
dict: {'num_obstacles': 5, 'object_size': 20, 'window_size': 512, 'action_step_scaling': 20, 'obstacle_step_scaling': 5, 'delta_T': 1, 'render_fps': 24, 'input_dims': 26, 'batch_size': 4096, 'gamma': 0.999, 'target_update': 10, 'alpha': 0.0003, 'beta': 0.0003, 'tau': 0.005, 'entropy_factor': 0.5, 'entropy_factor_final': 0.5, 'num_episodes': 3000, 'sigma_init': 2.0, 'sigma_final': 2.0, 'pretrain': True, 'num_episodes_pretrain': 1000, 'maxsize_ReplayMemory': 100000, 'action_smoothing': False, 'action_history_size': 3, 'select_action_filter': False, 'select_action_filter_after_episode': 70, 'sort_obstacles': True, 'apply_environment_seed': False, 'seed_init_value': 3407, 'plot_durations': False, 'plot_sigma': False, 'scheduler_period': 2}